### ISSUE TITLE
import static resource error 

### ISSUE THREAD

**Issue by patrick-Xu** [joeldenning/vite-single-spa-example#4]
Error when i import static resource，any solution for that？thank you.

![image](https://user-images.githubusercontent.com/40697435/117547451-45d80280-b062-11eb-826c-05d94d6f524e.png)

![image](https://user-images.githubusercontent.com/40697435/117547456-4a042000-b062-11eb-8d1c-2c249d5c7b1a.png)

**Comment by lovetingyuan** [comment]
https://github.com/vitejs/vite/issues/3107 the same issue

**Comment by lovetingyuan** [comment]
https://github.com/vuejs/vue-next/pull/2477 does this work correctly?

**Comment by patrick-Xu** [comment]
Host url is the current server path. 

![image](https://user-images.githubusercontent.com/40697435/117752245-06b7d600-b249-11eb-9f60-659761ab2a1d.png)

**Comment by patrick-Xu** [comment]
Url is the current server path.
![image](https://user-images.githubusercontent.com/40697435/117752779-f6542b00-b249-11eb-88d6-d7095d0a11b0.png)

**Comment by internettrans** [comment]
I commented at https://github.com/vitejs/vite/issues/3107#issuecomment-840688149 with an update on this. It seems that Vite 2 seems to have broken this, as originally https://github.com/vuejs/vue-next/pull/2477 was all that was needed to support this. But now Vite 2 is modifying the base during the serve target in a way that breaks things.

**Comment by internettrans** [comment]
Going to close this in favor of https://github.com/vitejs/vite/issues/3107. Later, I may be able to look further into that issue to create a pull request to fix it. However i spent a couple hours on it now and need to move onto other things for the rest of the day (have >100 github issues and slack messages to respond to!)

**Comment by patrick-Xu** [comment]
it didn find this resource in parent application in localhost 8080 ，the correct one should be the child application in localhost 3000。how can i solve this problem？
![image](https://user-images.githubusercontent.com/40697435/118295820-dacd7680-b50e-11eb-9d41-ceeda4aae713.png)

**Comment by internettrans** [comment]
My comments above explain this - it's a bug in Vite. The issue linked to above is the tracking issue within Vite for this.
