### ISSUE TITLE
browser keep refreshing

### ISSUE THREAD

**Issue by patrick-Xu** [joeldenning/vite-single-spa-example#5]
browser keep refreshing when open https://single-spa-playground.org/playground/instant-test?name=vite-test&framework=vue&useNativeModules=true&url=https%3A%2F%2Flocalhost%3A3000%2Fsrc%2Fmain.js  in dev envirnment

**Comment by internettrans** [comment]
I just pushed https://github.com/joeldenning/vite-single-spa-example/commit/55c2258c687d89a65c7eefa1567a75bf7f12a6a9 which has various updates. I do not see constant refreshes with that commit. Can you try it and let me know if it's still happenign for you?

**Comment by rastislavsvoboda** [comment]
tested today, and browser still keeps refreshing (tested with chrome and edge)

**Comment by internettrans** [comment]
I just tried this out and didn't see the problem. Make sure to follow the instructions exactly, including using `pnpm` rather than npm or yarn. Feel free to comment further, or create a new issue if the issue persists and you have more information about how to reproduce the problem.
